# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: r
dist: trusty
cache: packages
sudo: false

before_install: 
  - curl -OL https://raw.githubusercontent.com/metacran/r-builder/master/pkg-build.sh
  - chmod 755 pkg-build.sh
  
r_packages:
    - covr
    - devtools 


install:
  - ./pkg-build.sh install_deps install_bioc_deps
  - ./pkg-build.sh install_github r-lib/testthat
  - ./pkg-build.sh install_github mskilab/gUtils
  - ./pkg-build.sh install_github r-lib/covr

script: ./pkg-build.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

after_success:
  - Rscript -e 'covr::codecov()'
  
notifications:
  email:
    on_success: change
    on_failure: change
